default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: yym
  password: 123456
  host: localhost
  port: 5001
development:
  <<: *default
  database: xdml_record_money_rails_development
test:
  <<: *default
  database: xdml_record_money_rails_test
production:
  <<: *default
  database: xdml_record_money_rails_production
  username: xdml_record_money_rails
  password: <%= ENV['XDML_RECORD_MONEY_RAILS_DATABASE_PASSWORD'] %>
